# Generated by Django 4.2.7 on 2023-11-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('Images', models.ImageField(upload_to='new_pic')),
            ],
        ),
    ]
