# Generated by Django 4.2.7 on 2023-12-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospital',
            new_name='Hospital_table',
        ),
    ]
